const TEST_ACTIONS = {
  UPDATE_QUESTIONS: 'UPDATE_QUESTIONS',
  UPDATE_CURRENT_QUESTION: 'UPDATE_CURRENT_QUESTION',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  UPDATE_RESULT: 'UPDATE_RESULT',
  CLEAR_TEST: 'CLEAR_TEST',
};
export default TEST_ACTIONS;
